### ISSUE TITLE
An error occurred: No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by evaldasou** [heptio/ark#10]
Hey Heptio Team,

After I run :` "ark backup create nginx-backup --selector app=nginx"`
I get this : 
`"An error occurred: No Auth Provider found for name "gcp"`

**Comment by ncdc** [comment]
Hi @evaldasou, thanks for this report.

Are you running `ark` using the aliased command we have in our readme? Are you running on gcp? Any additional details you can provide will help us narrow down the issue. Thanks!

**Comment by evaldasou** [comment]
Thanks for quick response @ncdc , I run it on my local machine using alias command. 
My Kubernetes cluster is running on GCP (but I execute command directly on my machine, not on cluster node).

Should I run it on Kubernetes node directly? Thanks!

**Comment by ncdc** [comment]
@evaldasou no, you can run it on your local machine. Would you be willing to share your kubeconfig, redacting anything secret such as certificates/credentials?

**Comment by ncdc** [comment]
Ah I think I might have figured it out. We might need to pull in some auth provider plugin code from client-go for gcp, azure, and oidc. Can you confirm that your kubeconfig file has an `auth-provider` section?

**Comment by evaldasou** [comment]
Yes, there is `auth-provider `section : 
```
    auth-provider:
      config:
        access-token: <output ommited>
        cmd-args: config config-helper --format=json
        cmd-path: /root/google-cloud-sdk/bin/gcloud
        expiry: 2017-08-07T14:37:53Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
