### ISSUE TITLE
Make it easy to add/remove plugins

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#210]
This is what I've been testing for a plugin installation mechanism:

1. Create a docker image (from alpine) that contains the plugin binaries in `/plugins` inside the image
1. Set the image's entrypoint to `["sh", "-c", "cp -a /plugins/* /target/."]` (this copies everything from `/plugins` to `/target`, where `/target` is actually a volume mount for `/plugins` in the `ark` container)
1. In the `ark` deployment, add an init container like this:
```yaml
- name: objectstore-andy
  image: gcr.io/heptio-images/ark-plugin-example:latest
  imagePullPolicy: IfNotPresent
  volumeMounts:
    - name: plugins
      mountPath: /target
```
4. In the `ark` deployment, add a volume like this:
```yaml
- name: plugins
  emptyDir: {}
```
5. In the `ark` deployment, add a volume mount for the `ark` container like this:
```yaml
- name: plugins
  mountPath: /plugins
```

I think this could be simplified if
1. By default, the `ark` deployment has the `plugins` volume & volume mount
1. We add `ark plugin add` and `ark plugin remove` to manipulate the init containers
