### ISSUE TITLE
Simplify deployment yaml

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#25]
I think we can simplify the deployment yaml to be cloud-provider agnostic. Right now the "common" one is used for AWS and GCP and it contains this snippet:

```yaml
env:
  - name: AWS_SHARED_CREDENTIALS_FILE
    value: /credentials/cloud
```

Our GCP instructions say you need to rename `AWS_SHARED_CREDENTIALS_FILE` to `GOOGLE_APPLICATION_CREDENTIALS`, so it's not really a "common" file since you have to edit it for GCP.

For Azure, we have a different file where everything is identical except instead of using a `volume`/`volumeMount` to specify the cloud provider credentials, we expose all the data in our secret as environment variables:

```yaml
envFrom:
  - secretRef:
      name: cloud-credentials
```

I propose we consider this:

1. Remove the Azure deployment yaml
1. Remove the `env` section from the common deployment
1. Modify our `cloud-credentials` secret:
    1. Add a new require key, `provider` (valid values `aws`, `azure`, `gcp`)
    1. The remainder of the file is provider-specific
1. Modify our server code to look at the `provider` value and proceed appropriately

WDYT @skriss @abiogenesis-now?
