### ISSUE TITLE
Different namespace for backup

### ISSUE THREAD

**Issue by AdityaTulasi** [heptio/ark#291]
Hi,

I am using Kubernetes on Azure (AKS). I am trying to setup backup in a namespace different from "heptio-ark", because I cannot create a service principal with name "heptio-ark" (technical issues). I have changed the namespace in all configuration files and deployed the containers, but when I look at the logs of "ark-2601286424-h74xx" pod, I see that it is still searching for "heptio-ark" namespace. I created the cloud-secrets in the new namespace (heptio-ark-adit). Can you please let me know if this scenario is supported or not? If yes, then please help me with what I am missing.

P.S.: I apologize if this is not the right channel to post this question. 

# Full details

**Pods in the cluster**

```
PS C:\WINDOWS\system32> kubectl get pods --all-namespaces
NAMESPACE         NAME                                    READY     STATUS    RESTARTS   AGE
heptio-ark-adit   ark-2601286424-h74xx                    1/1       Running   0          1h
kube-system       heapster-2574232661-g57k2               2/2       Running   0          1h
kube-system       kube-dns-v20-2253765213-dl7g1           3/3       Running   0          1h
kube-system       kube-dns-v20-2253765213-gtgxp           3/3       Running   0          1h
kube-system       kube-proxy-s69h4                        1/1       Running   0          1h
kube-system       kube-svc-redirect-l87t3                 1/1       Running   0          1h
kube-system       kubernetes-dashboard-2898242510-1c1dz   1/1       Running   0          1h
kube-system       tunnelfront-930269083-n4nch             1/1       Running   0          1h
PS C:\WINDOWS\system32>
```
**Logs of the pod (initial)**
```
time="2018-02-01T06:33:26Z" level=info msg="setting log-level to INFO"
time="2018-02-01T06:33:26Z" level=info msg="Starting Ark server v0.6.0" logSource="pkg/cmd/server/server.go:86"
time="2018-02-01T06:33:26Z" level=info msg="Ensuring namespace exists for backups" logSource="pkg/cmd/server/server.go:222" namespace=heptio-ark
time="2018-02-01T06:33:27Z" level=info msg="Namespace created" logSource="pkg/cmd/server/server.go:230" namespace=heptio-ark
time="2018-02-01T06:33:27Z" level=info msg="Namespace already exists" logSource="pkg/cmd/server/server.go:234" namespace=heptio-ark
time="2018-02-01T06:33:27Z" level=info msg="Retrieving Ark configuration" logSource="pkg/cmd/server/server.go:239"
time="2018-02-01T06:33:27Z" level=info msg="Configuration not found" logSource="pkg/cmd/server/server.go:252"
time="2018-02-01T06:33:27Z" level=info msg="Will attempt to retrieve configuration again in 5 seconds" logSource="pkg/cmd/server/server.go:254"

```

**Commands executed**
```
kubectl create secret generic cloud-credentials --namespace heptio-ark-adit --from-literal AZURE_SUBSCRIPTION_ID="<guid>" --from-literal AZURE_TENANT_ID="<guid>" --from-literal AZURE_RESOURCE_GROUP="adit-aks-rg" --from-literal AZURE_CLIENT_ID="<appID>"   --from-literal AZURE_CLIENT_SECRET="<Password>" --from-literal AZURE_STORAGE_ACCOUNT_ID="aditaks" --from-literal AZURE_STORAGE_KEY="<key>"

kubectl apply -f .\examples\common\00-prereqs.yaml

kubectl apply -f .\examples\azure\
```
## File contents

**examples/azure/00-ark-deployment.yaml**

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: heptio-ark-adit
  name: ark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: ark
    spec:
      restartPolicy: Always
      serviceAccountName: ark
      containers:
        - name: ark
          image: gcr.io/heptio-images/ark:latest
          command:
            - /ark
          args:
            - server
          envFrom:
            - secretRef:
                name: cloud-credentials
          volumeMounts:
          - name: plugins
            mountPath: /plugins
      volumes:
        - name: plugins
          emptyDir: {}
```

**examples/azure/10-ark-config.yaml**

```
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: heptio-ark-adit
  name: default
persistentVolumeProvider:
  name: azure
  config:
    location: "East US"
    apiTimeout: 30m
backupStorageProvider:
  name: azure
  bucket: ark
backupSyncPeriod: 30m
gcSyncPeriod: 30m
scheduleSyncPeriod: 1m
restoreOnlyMode: false
```

**examples/common/00-prereqs.yaml**

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backups.ark.heptio.com
  labels:
    component: ark
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: backups
    kind: Backup
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: schedules.ark.heptio.com
  labels:
    component: ark
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: schedules
    kind: Schedule

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: restores.ark.heptio.com
  labels:
    component: ark
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: restores
    kind: Restore

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configs.ark.heptio.com
  labels:
    component: ark
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: configs
    kind: Config

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: downloadrequests.ark.heptio.com
  labels:
    component: ark
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: downloadrequests
    kind: DownloadRequest

---
apiVersion: v1
kind: Namespace
metadata:
  name: heptio-ark-adit

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ark
  namespace: heptio-ark-adit
  labels:
    component: ark

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ark
  labels:
    component: ark
subjects:
  - kind: ServiceAccount
    namespace: heptio-ark-adit
    name: ark
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: heptio-ark-adit
  name: ark
  labels:
    component: ark
rules:
  - apiGroups:
      - ark.heptio.com
    verbs:
      - "*"
    resources:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: heptio-ark-adit
  name: ark
  labels:
    component: ark
subjects:
  - kind: ServiceAccount
    namespace: heptio-ark-adit
    name: ark
roleRef:
  kind: Role
  name: ark
  apiGroup: rbac.authorization.k8s.io
```

**examples/common/10-deployment.yaml**

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: heptio-ark-adit
  name: ark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: ark
    spec:
      restartPolicy: Always
      serviceAccountName: ark
      containers:
        - name: ark
          image: gcr.io/heptio-images/ark:latest
          command:
            - /ark
          args:
            - server
          volumeMounts:
            - name: cloud-credentials
              mountPath: /credentials
            - name: plugins
              mountPath: /plugins
          env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
      volumes:
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
        - name: plugins
          emptyDir: {}

```
