### ISSUE TITLE
Document how to set up a non-cluster-admin role & rolebinding for Ark users

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#350]
Consider `kubectl create role/rolebinding` and/or raw yaml

```
kubectl -n heptio-ark create role ark --verb='*' --resource='backups.ark.heptio.com,restores.ark.heptio.com,schedules.ark.heptio.com,config.ark.heptio.com'

kubectl -n heptio-ark create rolebinding --role=ark --user=YOUR_USER_HERE
```

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: heptio-ark
  name: ark
  labels:
    component: ark
rules:
  - apiGroups:
      - ark.heptio.com
    verbs:
      - "*"
    resources:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ark
subjects:
  - kind: User
    name: YOUR_USER_HERE
roleRef:
  kind: Role
  name: ark
  apiGroup: rbac.authorization.k8s.io
```
