### ISSUE TITLE
Error removing backups.ark.heptio.com objects

### ISSUE THREAD

**Issue by marco-jantke** [heptio/ark#376]
I deleted the `heptio-ark` namespace in order to test what happens in case of manual operator errors. This deleted all objects from the namespace properly, except the `backups.ark.heptio.com` objects. It did empty the GCP bucket, which is actually something I'd like to avoid as described in #375 but not the objects itself. When viewing the logs from the server it's full of this messages:

```
time="2018-03-13T07:42:14Z" level=info msg="Garbage-collecting backup" backup=heptio-ark/hcg-dev-dust-k8s-backup-20180310220008 logSource="pkg/controller/gc_controller.go:129"
time="2018-03-13T07:42:14Z" level=info msg="Removing backup from object storage" backup=heptio-ark/hcg-dev-dust-k8s-backup-20180310220008 logSource="pkg/controller/gc_controller.go:244"
time="2018-03-13T07:42:14Z" level=error msg="Error patching backup" backup=heptio-ark/hcg-dev-dust-k8s-backup-20180310220008 error="unable to find api field in struct Unstructured for the json field \"metadata\"" error.file="gc_controller.go:152" error.function="(*gcController).handleFinalizer" logSource="pkg/controller/gc_controller.go:152"
```

Also the heptio-ark namespace is still in state "Terminating".

I'm using ark version 0.7.1 and followed the GCP setup instructions. This is my config:

```
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: heptio-ark
  name: default
backupStorageProvider:
  name: gcp
  bucket: my-bucket
backupSyncPeriod: 60m
gcSyncPeriod: 60m
scheduleSyncPeriod: 1m
restoreOnlyMode: false
---
apiVersion: ark.heptio.com/v1
kind: Schedule
metadata:
  name: my-backup
  namespace: heptio-ark
spec:
  schedule: 0 * * * *
  template:
    includedNamespaces:
    - development
    - sandbox
    - heptio-ark
    includeClusterResources: false
    ttl: 336h0m0s # 2 weeks
```

And here the Kubernetes versions:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.7-gke.1", GitCommit:"192ccad06d24af9828cbf42330e1d915cb586406", GitTreeState:"clean", BuildDate:"2018-01-31T21:39:04Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
