### ISSUE TITLE
Project config on GCP file

### ISSUE THREAD

**Issue by adawolfs** [heptio/ark#400]
I have found that there is a commit to remove the project config from ark config file and get it from credentials but its actually not supported on examples, and giving this error

> An error occurred: rpc error: code = Unknown desc = missing project in gcp configuration

Please use this template
```
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: heptio-ark
  name: default
persistentVolumeProvider:
  name: gcp
  config:
    project: <YOUR_PROJECT> #Replace by your project id
backupStorageProvider:
  name: gcp
  bucket: <YOUR_BUCKET> #Replace by your bucket name
backupSyncPeriod: 30m
gcSyncPeriod: 30m
scheduleSyncPeriod: 1m
restoreOnlyMode: false
```
