### ISSUE TITLE
Add CRDs to list of prioritized resources

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#424]
**User Story**

As a cluster operator, I would like to use Ark to backup and restore my Kubernetes clusters which leverage Custom Resource Definitions.

As a Gimbal cluster operator, I would like to be able to use Ark to backup and restore my Gimbal cluster

---
We need to restore CRDs before we restore their associated CRs, so we need to add CRDs to the list of default resource priorities.

It would also be nice if we could wait for a CRD to be "ready" (as indicated in its `status`) before proceeding; otherwise, trying to create CRs for it might fail.

**Comment by skriss** [comment]
How exactly should "ready" be determined? Here's what I see in `.status` for the `backup.ark.heptio.com` CRD:

```
status:
  acceptedNames:
    kind: Backup
    listKind: BackupList
    plural: backups
    singular: backup
  conditions:
  - lastTransitionTime: 2018-04-17T18:07:24Z
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: 2018-04-17T18:07:24Z
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
```
