### ISSUE TITLE
Error starting ark-server

### ISSUE THREAD

**Issue by gianrubio** [heptio/ark#430]
I was trying to test the ark chart from https://github.com/kubernetes/charts/pull/3795 and I got a weird error. I compared this file with the same provided by the ark docs and they look pretty similar. No idea what's going on. This is happening in version 0.7.1 and 0.8.0-rc.1

## Logs
```
$ kubectl logs -f -n heptio-ark-server ark-server-6fcf6fb795-n7j8l
time="2018-04-17T09:03:20Z" level=info msg="setting log-level to INFO"
time="2018-04-17T09:03:20Z" level=info msg="Starting Ark server v0.8.0-rc.1" logSource="pkg/cmd/server/server.go:92"
time="2018-04-17T09:03:20Z" level=info msg="Ensuring namespace exists for backups" logSource="pkg/cmd/server/server.go:258" namespace=heptio-ark
time="2018-04-17T09:03:20Z" level=info msg="Namespace already exists" logSource="pkg/cmd/server/server.go:270" namespace=heptio-ark
time="2018-04-17T09:03:20Z" level=info msg="Retrieving Ark configuration" logSource="pkg/cmd/server/server.go:275"
time="2018-04-17T09:03:20Z" level=info msg="Successfully retrieved Ark configuration" logSource="pkg/cmd/server/server.go:293"
time="2018-04-17T09:03:20Z" level=info msg="Using default resource priorities" logSource="pkg/cmd/server/server.go:328" priorities="[namespaces persistentvolumes persistentvolumeclaims secrets configmaps serviceaccounts limitranges]"
time="2018-04-17T09:03:20Z" level=info msg="Configuring cloud provider for backup service" logSource="pkg/cmd/server/server.go:368"
An error occurred: plugin not found
```

## Deployment
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  generation: 3
  labels:
    app: ark-server
    component: ark
    release: ark-server
  name: ark-server
  namespace: heptio-ark-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ark-server
      component: ark
      release: ark-server
  template:
    metadata:
      labels:
        app: ark-server
        component: ark
        release: ark-server
    spec:
      containers:
      - args:
        - server
        - --namespace
        - heptio-ark
        command:
        - /ark
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        image: gcr.io/heptio-images/ark:latest
        imagePullPolicy: IfNotPresent
        name: ark
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /credentials
          name: cloud-credentials
        - mountPath: /plugins
          name: plugins
      serviceAccount: ark-server
      serviceAccountName: ark-server
      volumes:
      - name: cloud-credentials
        secret:
          defaultMode: 420
          secretName: cloud-credentials
      - emptyDir: {}
        name: plugins
```
