### ISSUE TITLE
Consider backing up pods from controllers (statefulsets, deployments, etc) even if pod labels don't match backup's label selector

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#445]
Scenario: I have a StatefulSet with label `foo=bar`. Its pods, however, do not have this label. We should consider backing up pods in this situation.

We may need to keep track of each "seen controller" and back up all items controlled by it. For example, if we back up Deployment X, we'd need to also back up ReplicaSet Y because it's controlled by Deployment X. And following through, we'd need to back up Pod(s) Z controlled by ReplicaSet Y.

**Comment by rosskukulinski** [comment]
So if I understand this correctly, if I have a StatefulSet as defined here:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  labels:
    foo: bar
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
```

Doing an `ark backup --selector foo:bar` will backup the StatefulSet, but not the Pods that the controller is managing.  This is because the Pods will only have a label app:nginx (plus whatever the ReplicaSet injects).

Correct so far?

While I could see someone thinking this is counter-intuitive, I’m inclined to vote for maintaining the existing labelSelector matching rules.  Users could update the Pod spec in StatefulSet/Deployment to have corresponding labels so that backups are enabled for the sub-resources.

That said, I could see us adding a `--backup-children` or similar option that will follow those relationships.

There would have to be a similar option on the restore side as well.
