### ISSUE TITLE
Support backing up to a folder in object storage

### ISSUE THREAD

**Issue by badbeeker** [heptio/ark#543]
Hello,

Nothing is listed in the documentation, but I was wondering if you can use a folder in an existing s3 bucket as a storage option instead of just the bucket name?

For example:
- heptio-ark-backups
  - cluster1
    - backup1
    - backup2
  - cluster2
    - backup1
  - cluster3
    - backup1

If so, would the configuration be:
```
backupStorageProvider:
  name: aws
  bucket: heptio-ark-backups/cluster1
  config:
    region: us-west-2
```
