### ISSUE TITLE
Add support for client-go exec auth plugins

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#565]
To support a kubeconfig with a user such as
```yaml
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "terraform-eks-demo"
```
