### ISSUE TITLE
Restic integration errors out

### ISSUE THREAD

**Issue by trondhindenes** [heptio/ark#567]
I'm trying to get restic up and running but it keeps failing. My ark config looks like this:
```
backupStorageProvider:
  name: aws
  bucket: stuff-dev-heptio-ark
  config:
    region: eu-west-1
  resticLocation: stuff-dev-heptio-ark-restic
```
(btw _please_ provide yaml files instead of fancy kubectl/jq commands to configure the required settings. While those are super-impressive, yaml is easier to read and understand. I have no idea what most of the commands in the restic documentation do, which makes it very hard to follow.

Here's the error I'm getting from the ark server:
```
time="2018-06-21T21:02:16Z" level=error msg="backup failed" error="error running command, stderr=Fatal: create repository at s3:s3.amazonaws.com/stuff-dev-heptio-ark-restic/nginx-example failed: client.BucketExists: The specified bucket does not exist.\n\n: exit status 1" key=heptio-ark/nginx-example logSource="pkg/controller/backup_controller.go:280"
```
Running ark without restic integration works, and the iam permissions are correct. The bucket exists, but maybe the restic integration expects a certain bucket location? AFAIK there's no `resticLocationRegion` setting or similar.
