### ISSUE TITLE
Define how to enable/disable and configure plugins

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#584]
For example, some users might not want to enable the plugins that automatically walk from pod to pvc to pv.

**Comment by ncdc** [comment]
Let's say we want to enable/disable and configure the "foo.com/pod" BackupItemAction. Possible options:

- Create a ConfigMap in the heptio-ark namespace, the name can be whatever:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo-com-pod-config
  labels:
    ark.heptio.com/plugin-config: foo.com/pod
data:
  enabled: false
  addAnnotations:
    color: green
    size: small
```

Let's say we just want to disable a plugin that has no configuration:

- add `--enable-plugins NAME(s)` and/or `--disable-plugins NAME(s)` flags to the `ark server`
- use ConfigMaps and Ark is responsible for checking for an enable/disable annotation:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo-com-pod-config
  labels:
    ark.heptio.com/plugin-config: foo.com/pod
    ark.heptio.com/plugin-enabled: false
```


Proposed approach:
1. Admin uses `--enable-plugins` and/or `--disable-plugins` flag for the `ark server` to control which plugins are enabled
1. Admin and/or users can create ConfigMaps to configure their plugins, assuming plugins support configuration
