### ISSUE TITLE
whether ark restore pv and pvc must  use cloud provider snapshot?

### ISSUE THREAD

**Issue by fumanne** [heptio/ark#727]
I'm testing restore function with ark, but met some question:
The following is my example with pv:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-example
  labels:
    app: nginx
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-logs
  namespace: nginx-example
  labels:
    app: nginx
spec:
  storageClassName: rook-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-logs
          persistentVolumeClaim:
           claimName: nginx-logs
      containers:
      - image: nginx:1.7.9
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false
```
1. I can backup this pod successfully with command  ark backup create ......
2. Then use ark logs .. it show complete in console, and I also see the backup file already in minio (compatible with aws s3)
3. next, I delete pod and pv,pvc.  use command ark create restore .....  and it successfully. the pod pv,pvc has created successfully!. but I go into the container (/var/log/nginx). There is no data in it!!
, The data is not restore!!
in log shows: "Not restoring PV because it doesn't have a snapshot and its reclaim policy is Delete"

**My environment is not in aws and gce, it is a third_party cloud provider**
so question:
whether ark can not support restore data in third_party cloud provider ?
