### ISSUE TITLE
POD + SA restores fail due to invalid token

### ISSUE THREAD

**Issue by james-powis** [heptio/ark#840]
**What steps did you take and what happened:**

Prerequisits: 
- Persistent volumes - I use https://github.com/vmware/vsphere-storage-for-kubernetes
- Restic configured ark
- Helm
- Ingress Controller (I use haproxy)

Steps to reproduce working example:
1. Create values-works.yaml:
```yaml
Master:
  ServiceType: ClusterIP
  HostName: jenkins.example.com
  PodAnnotations:
    backup.ark.heptio.com/backup-volumes: jenkins-home
Persistence:
  Enabled: true
  AccessMode: ReadWriteOnce
  Size: 8Gi
```
2. Deploy helm chart and create backup.
```
helm upgrade --install test-jenkins stable/jenkins -f values-works.yaml
# Monitor for everything being complete
ark create backup test-jenkins-works
# Monitor for backup completion.
```
3. Delete the helm chart and restore from backup
```
helm delete --purge test-jenkins
# Monitor for all objects being removed
ark create restore test-jenkins-works --from-backup test-jenkins-works
# Monitor the restore, it will complete successfully.
# Cleanup for next example:
helm delete --purge test-jenkins
```

Steps to create the issue which breaks the restore (all we are adding is the service account):
1. Create values-broken.yaml
```yaml
Master:
  ServiceType: ClusterIP
  HostName: jenkins.example.com
  PodAnnotations:
    backup.ark.heptio.com/backup-volumes: jenkins-home
Persistence:
  Enabled: true
  AccessMode: ReadWriteOnce
  Size: 8Gi
rbac:
  install: true
  serviceAccountName: jenkins
  apiVersion: v1
  roleRef: cluster-admin
  roleBindingKind: ClusterRoleBinding
```
2. Deploy helm chart and create backup.
```
helm upgrade --install test-jenkins stable/jenkins -f values-broken.yaml
# Monitor for everything being complete
ark create backup test-jenkins-broken
# Monitor for backup completion.
```
3. Delete the helm chart and restore from backup
```
helm delete --purge test-jenkins
# Monitor for all objects being removed
ark create restore test-jenkins-broken --from-backup test-jenkins-broken
# Monitor the restore, it will not complete
```

Cleanup... (note: this might not be the best way to clean everything up, but it worked for me.)

1. Delete the helm chart `helm delete --purge test-jenkins`
2. Remove the restore which is hung in progress: `ark delete restore test-jenkins`
3. For good measure delete the ark pod because it is hung, it will recreate automatically `kubectl -n heptio-ark delete pod ark-asdf1234`

**What did you expect to happen:**

As demonstrated from `kubectl get pod test-jenkins-asdf1234 -o yaml` we can see that restic injects an int controller into the pod, in the absence of the RBAC configurations, this is successful, but in the presence of RBAC this fails. The delta of these 2 different configs is here: https://gist.github.com/james-powis/b289b5a9467350e5dc7a95b12ec6388e

And the hung restore state can be observed here https://gist.github.com/james-powis/0b5854fb89784e4ce5e1b6aab9458f61

**Environment:**

- Ark version (use `ark version`):  
```
Version: v0.9.3
Git commit: v0.9.3
Git tree state: clean
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: 
```
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:14:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: vcenter/vsphere
- OS (e.g. from `/etc/os-release`):
```
# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
