### ISSUE TITLE
Failed to restore a Kubernetes volumes with restic and minio on bare-metal

### ISSUE THREAD

**Issue by ston3o** [heptio/ark#844]
**What steps did you take and what happened:**

I want to restore Kubernetes volumes with restic. Backup works, restoring too but not my persistent volumes.

- `kubectl apply -f examples/common/00-prereqs.yaml`

- `kubectl apply -f examples/minio/`

- `ark backup create test -l release=test`

- `kubectl -n heptio-ark get podvolumebackups` : 

```
NAME         AGE
test-9749b   2m
```

- `ark restore create --from-backup test`

- `kubectl -n heptio-ark get podvolumerestores` : 

```
No resources found.
```

**What did you expect to happen:**

`kubectl -n heptio-ark get podvolumerestores` show something and restore my persistent volume.

**The output of the following commands will help us better understand what's going on**:

* `kubectl logs deployment/ark -n heptio-ark` : http://termbin.com/l71h
* `ark backup describe <backupname>` or `kubectl get backup/<backupname> -n heptio-ark -o yaml` : http://termbin.com/7je2
* `ark backup logs <backupname>` : http://termbin.com/71rn
* `ark restore describe <restorename>` or `kubectl get restore/<restorename> -n heptio-ark -o yaml` : http://termbin.com/605k
* `ark restore logs <restorename>` : http://termbin.com/ev8p

**Anything else you would like to add:**

Here my `10-ark-config.yaml` : 

```yaml
---
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: heptio-ark
  name: default
persistentVolumeProvider:
  name: aws
  config:
    region: minio
backupStorageProvider:
  name: aws
  bucket: ark
  resticLocation: my-restic-bucket
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://minio.heptio-ark.svc:9000
```

**Environment:**

- Ark version:  `v0.9.4`
- Kubernetes version: `v1.10.0`
- Kubernetes installer & version: `v1.10.0`
- Cloud provider or hardware configuration: `minikube`
